### ISSUE TITLE
WXR error

### ISSUE THREAD

**Issue by Kenshino** [WPTRT/theme-unit-test#1]
So downloading the latest from this repo and importing into my WordPress installation results in 

This does not appear to be a WXR file, missing/invalid WXR version number.

The old version from 2015 Oct works ;/

**Comment by emiluzelac** [comment]
I would say that this is something on your end, just tested on one of my sites and it worked just fine:

> All done. Have fun!
> 
> Remember to update the passwords and roles of imported users.
