### ISSUE TITLE
Jet Pack Tests

### ISSUE THREAD

**Issue by khacoder** [WPTRT/theme-unit-test#12]
There are special tests in Theme Unit Test for Tiled Gallery and VideoPress.

As far as I can tell these JetPack plugins were moved to JetPack Pro?

If that is the case then these tests should be removed.

**Comment by khacoder** [comment]
Sorry did not realize the weird access on the new version.....but really why are we including these anyways?

**Comment by carolinan** [comment]
The tiled gallery is available in the free version of Jetpack.

**Comment by khacoder** [comment]
So....do we include tests for Contact Form 7?

**Comment by khacoder** [comment]
We should not be including any tests for plugins that are opt it.

**Comment by joyously** [comment]
And Woo too?

**Comment by khacoder** [comment]
I was going to add that :)

**Comment by carolinan** [comment]
So go ahead and submit a PR.

**Comment by khacoder** [comment]
i will if I can figure the GIT stuff out.....busy right now though....thanks for the suggestion.
