### ISSUE TITLE
Alt Text is duplicated for each image

### ISSUE THREAD

**Issue by MadtownLems** [WPTRT/theme-unit-test#14]
Each image's alt text is duplicated, which causes mysql errors after import (subqueries returning more than 1 row).

For example:

<wp:postmeta>
    <wp:meta_key>_wp_attachment_image_alt</wp:meta_key>
    <wp:meta_value><![CDATA[Golden Gate Bridge]]></wp:meta_value>
  </wp:postmeta>
  <wp:postmeta>
    <wp:meta_key>_wp_attachment_image_alt</wp:meta_key>
    <wp:meta_value><![CDATA[Golden Gate Bridge]]></wp:meta_value>
  </wp:postmeta>

**Comment by carolinan** [comment]
#25 should solve this.
