### ISSUE TITLE
wptest.io image links broken

### ISSUE THREAD

**Issue by DannyCooper** [WPTRT/theme-unit-test#16]
Example: themeunittestdata.wodpress.xml:1494

http://wptest.io/demo/wp-content/uploads/2011/01/dsc20050727_091048_222.jpg

**Comment by DannyCooper** [comment]
From what I can tell they need to be changed to this:

http://wptest.io/demo/wp-content/uploads**/sites/2**/2011/01/dsc20050727_091048_222.jpg

**Comment by ernilambar** [comment]
@DannyCooper Are you sure this is the correct repo? Did you meant to create issue here https://github.com/poststatus/wptest ?

**Comment by carolinan** [comment]
How important is the _original_import_url meta key? Does this cause any errors?

```
  <wp:postmeta>
    <wp:meta_key>_original_import_url</wp:meta_key>
    <wp:meta_value><![CDATA[http://wptest.io/demo/wp-content/uploads/2011/01/dsc20050727_091048_222.jpg]]></wp:meta_value>
  </wp:postmeta>
```

**Comment by DannyCooper** [comment]
> How important is the _original_import_url meta key? Does this cause any errors?
> 
> ```
>   <wp:postmeta>
>     <wp:meta_key>_original_import_url</wp:meta_key>
>     <wp:meta_value><![CDATA[http://wptest.io/demo/wp-content/uploads/2011/01/dsc20050727_091048_222.jpg]]></wp:meta_value>
>   </wp:postmeta>
> ```

Is there any value in keeping those links, considering they are broken?

**Comment by carolinan** [comment]
They have been removed,

**Comment by DannyCooper** [comment]
They are still in master - https://github.com/WPTRT/theme-unit-test/blob/d6301641f02b278f4a527b2cb0a0ad092f2322fe/themeunittestdata.wordpress.xml#L1438
