### ISSUE TITLE
Title With Markup does not have markup.

### ISSUE THREAD

**Issue by carolinan** [WPTRT/theme-unit-test#2]
To be able to test this, the title needs to have markup.
`<title>Markup: Title With Markup</title>`
should be  
`<title>Markup: Title <em>With</em> <b>Markup</b></title>`

**Comment by jocastaneda** [comment]
Was this fixed with the merge? If so, I think we can close this one.

**Comment by emiluzelac** [comment]
I believe so.

**Comment by joyously** [comment]
The current state of things is that the markup is in the xml, but it is stripped out during import. Even the words are stripped out.
