### ISSUE TITLE
Add tests for editor blocks (Gutenberg)

### ISSUE THREAD

**Issue by carolinan** [WPTRT/theme-unit-test#23]
We need to add examples of editor blocks so that theme authors can test them easily.

I will include this link as an example:
https://github.com/thatplugincompany/block-unit-test

**Comment by carolinan** [comment]
@richtabor Would you be interested in helping out with this?

**Comment by richtabor** [comment]
@carolinan Sure! What do you think would be the best way to implement the tests?

**Comment by joyously** [comment]
I would think you would use a test site that has Gutenberg, create posts with a few of the blocks that make sense together, and export them. Then edit the unit test xml file and put the exported block posts in with the rest.

**Comment by joyously** [comment]
Looking at the branch for blocks, the video used in the common block post is `.mov` which is not supported everywhere. I see it as just a gray box with hard to read text saying the mime type is not supported.

![mov-video-not-supported](https://user-images.githubusercontent.com/7957680/48099577-a95ced00-e1e5-11e8-8f2d-de75a83b59c6.jpg)

**Comment by carolinan** [comment]
Yeah, the wordpress.com account where the files are hosted is a free account so I was not allowed to upload a new video.
I had to use the only video that was already uploaded.
I have asked Otto for help but no reply yet.

**Comment by carolinan** [comment]
The block branch has been merged into master. We can open new issues when new blocks are added to core.
