### ISSUE TITLE
read more & page break blocks not displaying

### ISSUE THREAD

**Issue by timelsass** [WPTRT/theme-unit-test#39]
To replicate:
1. Use twentynineteen (it also occurs on other themes) 
2. Install and activate the theme unit test data XML.
   - Note: I did select the author _Theme Buster_ to have posts assigned to my user, _time_ and _Theme Reviewer_ I left alone.

3. Go to the "Block category: Layout Elements" page, and scroll down to the last two tests.

These indicate a read more block should be displayed followed by a page break, but this is what I see:

![image](https://user-images.githubusercontent.com/11907254/54399265-fec57100-4693-11e9-85ba-49333c000c77.png)

This is the html in console if that is helpful:

![image](https://user-images.githubusercontent.com/11907254/54399382-84492100-4694-11e9-919b-994ef1412697.png)

**Comment by joyously** [comment]
Yeah, the text isn't correct. I'll make a PR.

**Comment by joyously** [comment]
I made PR #40 for this.

**Comment by carolinan** [comment]
Merged, thank you!
