### ISSUE TITLE
Revise existing users

### ISSUE THREAD

**Issue by carolinan** [WPTRT/theme-unit-test#4]
Do we need any users other than themedemos?
The menu items and images from Chip, Emil and Lance can be transferred over to the themedemos user.

If we need the users for anything else, the personal e-mails should probably be replaced.

**Comment by mor10** [comment]
Users with proper Gravatars are important for themes that display user info in different ways. I would suggest having at least one user with a Gravatar and one without.

During testing of one of my custom themes, I discovered that some of the users in the unit test don't have email addresses attached to them. This causes a problem, and is a situation that isn't normally possible, so I would suggest having all users have proper email addresses, even if they are dummy addresses solely for this purpose.

**Comment by emiluzelac** [comment]
Agreed with Morten, so far we didn't have any issues with addresses and
it's nice to have a real face when reviewing too ;)

**Comment by carolinan** [comment]
There are users that only has menu data and uploaded images, no posts pages or comments.

**Comment by carolinan** [comment]
Emil, Chip and Lance have been removed, but the comments  still needs to be fixed.

**Comment by carolinan** [comment]
https://github.com/WPTRT/theme-unit-test/pull/24#issuecomment-431611975

> Why do they have to be real email addresses?
> I was just referring to the fact that it's nice to have multiple authors (with different choices of display name so that that is tested), for showing in the author archives, and in the author bio.
> Comments should have a range of people also, to test the avatars and site links and whether the commenter is the author of the post.
> I think a bunch of this might need to be manually tweaked after import, though. If so, the various page tests should mention it.

A new user, **Theme Reviewer /  themereviewteam** has been added, This user does not currently have any posts or comments in the master branch.
This user does not have a gravatar, so now we have one user with and one without.

All commenters does not need to have a real email addresses, I believe example.com /.org is fine.

I have had a closer look and there are only a few email addresses that belong to existing third party domains, that needs to be removed:
admin@admin.com
fake@email.com
auser@kopasoft.com
And then there are two personal email addresses, I think they should be removed as well since this data is used on so many sites.

**Comment by carolinan** [comment]
Also, how do we handle the wp:comment_author_IP and GDPR?
