### ISSUE TITLE
When using test data block validation error in console for Block Gallery post

### ISSUE THREAD

**Issue by pallavic27** [WPTRT/theme-unit-test#41]
Please follow these steps

Import WordPress test data from Theme unit test data page
Edit "Block: Gallery" post
Right click and Inspect element
Go to console
Can see this error
Block validation: Block validation failed for core/spacer ({name: "core/spacer", title: "Spacer", description: "Add white space between blocks and customize its height.", icon: {…}, category: "layout", …}).

**Comment by carolinan** [comment]
The problem has been solved now, thank you.
