### ISSUE TITLE
Menu problems

### ISSUE THREAD

**Issue by joyously** [WPTRT/theme-unit-test#42]
I imported into a new site, and the All Pages Flat menu was empty. The Testing menu had duplicate entries for Page Image Alignment and Page Markup And Formatting.

**Comment by carolinan** [comment]
I can reproduce this.
I would also like to remove the Home menu item that points to WordPress.com.

**Comment by carolinan** [comment]
Solved with https://github.com/WPTRT/theme-unit-test/commit/20bd2e57ae663eee3620ce03f91768976c61eae1
