### ISSUE TITLE
Include the blocks added in WP 5.2

### ISSUE THREAD

**Issue by carolinan** [WPTRT/theme-unit-test#44]
The new blocks are:
 RSS, Search, Calendar, Tag Cloud, and Amazon Kindle

The current file does not include all embeds, so should we skip Kindle too?

**Comment by joyously** [comment]
I added RSS, Search, Calendar, Tag Cloud in #56.
See https://github.com/WPTRT/theme-unit-test/blob/014d28d002d546e67edd7170e6415e3290d1e486/themeunittestdata.wordpress.xml#L10280
