### ISSUE TITLE
"This block contains unexpected or invalid content"

### ISSUE THREAD

**Issue by pixedelic** [WPTRT/theme-unit-test#45]
I see this in the latest release of theme-test-unit:
![screen_shot_2019-04-17_at_10 16 50](https://user-images.githubusercontent.com/527057/56272178-77d44000-60fa-11e9-905f-35c8354bbeec.png)
due, it seems, to this:
![screen_shot_2019-04-17_at_10 14 48](https://user-images.githubusercontent.com/527057/56272234-93d7e180-60fa-11e9-9107-85df814fb297.jpg)
Tested with Twenty-Nineteen as well.

**Comment by joyously** [comment]
PR #47 fixes it.

**Comment by carolinan** [comment]
Thank you!
