### ISSUE TITLE
Invalid time on one of the posts in exported XML

### ISSUE THREAD

**Issue by Rarst** [WPTRT/theme-unit-test#52]
One of the posts in export file has invalid time of `19:57:357`

https://github.com/WPTRT/theme-unit-test/blob/8754eade34b536788214f89567ff62759d106de6/themeunittestdata.wordpress.xml#L3870

No idea how it ended up like that, using the file as test data and my code trips up on this.

**Comment by joyously** [comment]
That was probably my fault. I recently adjusted the times on the Blocks posts because they all had the same time and would come out in a random order.

**Comment by joyously** [comment]
Well, I looked at that PR and it wasn't in there, so it was probably some earlier attempt. #53 corrects it.

**Comment by carolinan** [comment]
Merged, closing, thank you!
