### ISSUE TITLE
Convert classic content to Gutenberg block

### ISSUE THREAD

**Issue by giorgioriccardi** [WPTRT/theme-unit-test#57]
I wonder if we should update the test data to Gutenberg blocks, or at least to create a version specifically converted in blocks?
If this can help or if interested at all, I could provide a converted version of the classic content into Gutenberg blocks.

**Comment by joyously** [comment]
There will always be sites that have legacy content, so the unit test should cover them also. 
This is a duplicate of #34.

**Comment by giorgioriccardi** [comment]
Thanks @joyously I totally missed #34 and further more [https://github.com/WPTRT/theme-unit-test/issues/34#issuecomment-444913549](https://github.com/WPTRT/theme-unit-test/issues/34#issuecomment-444913549)
